# Generated by Django 2.1.3 on 2019-07-10 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100, verbose_name='费用名称')),
                ('c_price', models.IntegerField(verbose_name='费用价格')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_BedID', models.CharField(max_length=10, verbose_name='床位号')),
                ('h_cash_pledge', models.IntegerField(verbose_name='缴费押金')),
                ('h_disease', models.CharField(max_length=150, verbose_name='病情')),
                ('h_status', models.SmallIntegerField(choices=[(1, '已住院'), (2, '已出院'), (3, '已结算')], verbose_name='住院状态')),
                ('h_time', models.DateTimeField(auto_now_add=True, verbose_name='入院时间')),
                ('h_nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='护理人员信息')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('r_ID_number', models.CharField(max_length=18, verbose_name='身份证号')),
                ('r_social_security', models.IntegerField(verbose_name='社保号')),
                ('r_registration_fee', models.IntegerField(verbose_name='挂号费')),
                ('r_phone', models.IntegerField(verbose_name='电话号')),
                ('r_self_paying', models.SmallIntegerField(choices=[(1, '自费'), (2, '不自费')], verbose_name='是否自费')),
                ('r_sex', models.CharField(max_length=2, verbose_name='性别')),
                ('r_age', models.IntegerField(verbose_name='年龄')),
                ('r_profession', models.CharField(max_length=50, verbose_name='职业')),
                ('r_examination', models.SmallIntegerField(choices=[(1, '初诊'), (2, '复诊')], verbose_name='初复诊')),
                ('r_remarks', models.CharField(max_length=100, verbose_name='备注')),
                ('r_time', models.DateTimeField(auto_now_add=True, verbose_name='挂号时间')),
                ('r_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Doctor', verbose_name='所挂医生')),
                ('r_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Section', verbose_name='所挂科室')),
            ],
        ),
        migrations.AddField(
            model_name='hospital',
            name='h_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Registration', verbose_name='挂号表信息'),
        ),
        migrations.AddField(
            model_name='cost',
            name='c_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Registration', verbose_name='挂号信息'),
        ),
    ]
