# Generated by Django 2.1.3 on 2019-07-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='r_status',
            field=models.SmallIntegerField(choices=[(1, '已挂号'), (2, '已住院'), (3, '已退号')], default=1, verbose_name='挂号状态'),
        ),
    ]
