# Generated by Django 2.1.3 on 2019-07-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='d_inventory',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='d_status',
        ),
        migrations.AlterField(
            model_name='drug',
            name='d_describe',
            field=models.CharField(max_length=500, verbose_name='药品简述描述'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='d_remarks',
            field=models.CharField(max_length=1000, verbose_name='备注'),
        ),
    ]
