# Generated by Django 2.1.3 on 2019-07-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20190716_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='d_inventory',
            field=models.IntegerField(default=2000, verbose_name='药品库存'),
        ),
        migrations.AddField(
            model_name='drug',
            name='d_status',
            field=models.SmallIntegerField(choices=[(1, '在售'), (2, '停售')], default='在售', verbose_name='药品状态'),
        ),
    ]
