# Generated by Django 2.1.3 on 2019-07-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_auto_20190716_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='d_inventory',
        ),
        migrations.AddField(
            model_name='drug',
            name='d_inventor',
            field=models.IntegerField(default=2000, verbose_name='药品库存'),
            preserve_default=False,
        ),
    ]
