# Generated by Django 2.1.3 on 2019-07-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurisdiction',
            name='j_jurisdiction',
            field=models.ManyToManyField(to='user.Role'),
        ),
    ]
